name: SpigotUtils
version: 1.1
api-version: 1.20
author: Delta203

main: de.spigotutils.delta203.spigot.SpigotUtilsSpigot

commands:
  test:
    description: Just a test command
    permission: test.use